// Run after starting a clean review server on port 8017.
const {chromium} = require('../.runtime/browser/node_modules/playwright');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const browser = await chromium.launch({headless:true,
    executablePath:process.env.STUDIO_BROWSER || 'C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe'});
  const page = await browser.newPage({viewport:{width:1440,height:1000}, reducedMotion:'reduce'});
  async function goTo(surface) {
    if(await page.locator('#mobile-menu').isVisible() && await page.locator('#mobile-menu').getAttribute('aria-expanded') !== 'true') await page.locator('#mobile-menu').click();
    await page.locator(`nav [data-view=${surface}]`).click();
  }
  const errors=[]; page.on('pageerror', error=>errors.push(error.message));
  const failed=[];page.on('response',response=>{if(response.url().includes('127.0.0.1') && response.status()>=400)failed.push(`${response.status()} ${response.url()}`);});
  await page.goto('http://127.0.0.1:8017',{waitUntil:'domcontentloaded'});
  await page.getByText('● Connected',{exact:true}).waitFor();
  await page.screenshot({path:'.runtime/studio-sources-empty.png',fullPage:true});
  await page.getByRole('button',{name:/Try the Biology demo/}).click();
  await page.locator('.lesson').first().waitFor({timeout:60000});
  await page.waitForFunction(()=>!document.getElementById('demo').disabled);
  await page.screenshot({path:'.runtime/studio-plan.png',fullPage:true});
  await page.getByRole('button',{name:/Preview closure dates/}).click();
  await page.locator('#closure-preview').getByText(/2026-10-08/).waitFor();
  await page.getByRole('button',{name:/Compare recovery strategies/}).click();
  await page.locator('#recovery-dialog[open]').waitFor({timeout:60000});
  await page.screenshot({path:'.runtime/studio-recovery-lab.png',fullPage:true});
  await page.locator('[data-strategy=coverage]').click();
  await page.locator('#diff .diff-item').first().waitFor({timeout:60000});
  await page.waitForFunction(()=>!document.getElementById('replan').disabled);
  const diff=await page.locator('#diff').innerText();
  if(!diff.toLowerCase().includes('compressed'))throw new Error('Replan did not show compression: '+diff);
  await page.screenshot({path:'.runtime/studio-replan.png',fullPage:true});
  await goTo('overview');
  await page.locator('.ledger tbody tr').first().waitFor();
  await page.screenshot({path:'.runtime/studio-overview.png',fullPage:true});
  await goTo('plan');
  await page.locator('.lesson').first().click();
  await page.locator('#inspector[open]').waitFor();
  await page.getByRole('button',{name:'Mark this session taught',exact:true}).click();
  await page.waitForFunction(()=>!document.getElementById('inspector').open);
  await page.getByRole('button',{name:/Simulate 100 disruptions/}).click();
  await page.locator('.forecast-number').waitFor({timeout:60000});
  await page.getByRole('button',{name:/Simulate 100 disruptions/}).waitFor();
  await page.screenshot({path:'.runtime/studio-forecast.png',fullPage:true});
  await goTo('evidence');
  await page.locator('.claim').first().waitFor();
  await page.locator('.claim').first().click();
  await page.locator('#pdf-preview canvas').waitFor({timeout:30000});
  await page.locator('.bbox-overlay').first().waitFor();
  await page.screenshot({path:'.runtime/studio-pdf-evidence.png',fullPage:true});
  await page.getByRole('button',{name:'Close evidence inspector'}).click();
  await page.locator('#audit-text').fill('Enzymes are biological catalysts.\nEnzymes work equally well at every temperature.\nBIO.FAKE.99 is an official objective.');
  await page.getByRole('button',{name:/Audit against my sources/}).click();
  await page.locator('#audit-results .audit-row').first().waitFor();
  if(!(await page.locator('#audit-results').innerText()).toLowerCase().includes('unknown code'))throw new Error('Unknown curriculum code was not flagged');
  await page.screenshot({path:'.runtime/studio-evidence.png',fullPage:true});
  await goTo('sources');
  await page.locator('[data-document]').first().click();
  await page.locator('[data-span]').first().waitFor();
  await page.screenshot({path:'.runtime/studio-sources.png',fullPage:true});
  await page.locator('#theme').click();
  await page.screenshot({path:'.runtime/studio-dark.png',fullPage:true});
  await page.locator('#theme').click();
  const pdfResponse=await page.request.get('http://127.0.0.1:8017/demo-biology.pdf');
  if(pdfResponse.status()!==200)throw new Error('Offline source PDF unavailable');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'.runtime/studio-mobile.png',fullPage:true});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  if(overflow)throw new Error('Mobile page overflows viewport');
  await page.setViewportSize({width:1000,height:1200});
  await page.evaluate(async()=>{
    const id=localStorage.getItem('studio-plan');
    const response=await fetch(`/planning/plans/${id}/export.pdf`);
    if(!response.ok)throw new Error('Plan PDF export failed');
    const pdfjs=await import('/vendor/pdfjs/pdf.mjs');
    pdfjs.GlobalWorkerOptions.workerSrc='/vendor/pdfjs/pdf.worker.mjs';
    const pdf=await pdfjs.getDocument({data:await response.arrayBuffer()}).promise;
    const first=await pdf.getPage(1),viewport=first.getViewport({scale:1.25});
    const canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;
    document.body.replaceChildren(canvas);document.body.style.cssText='padding:24px;background:#eee;display:flex;justify-content:center;';
    await first.render({canvasContext:canvas.getContext('2d'),viewport}).promise;
  });
  await page.screenshot({path:'.runtime/studio-plan-export.png',fullPage:true});
  fs.writeFileSync(path.resolve('.runtime/browser-verification.json'),JSON.stringify({errors,failed,mobileOverflow:overflow,diff},null,2));
  await browser.close();
  if(errors.length||failed.length)throw new Error(JSON.stringify({errors,failed}));
  console.log('Browser verification passed: demo, replan compression, lesson inspector, audit, sources, mobile layout.');
})().catch(error=>{console.error(error);process.exit(1);});
